### ISSUE TITLE
Broken with pixi.js@8.10.2

### ISSUE THREAD

**Issue by galloppinggryphon** [davidfig/pixi-viewport#523]
There seems to have been a number of breaking changes in pixi.js@8.5.2 (from your devDependencies). TS reports numerous type incompatibilities and it does not run (`container.updateLocalTransform is not a function`).  I haven't tried any versions in-between so I don't know when it broke, but it works with 8.5.2.
