### ISSUE TITLE
Typescript definition issues

### ISSUE THREAD

**Issue by uahic** [davidfig/pixi-viewport#84]
Hi there,

first of all: thank you for your effort in this project!
I work with Angular >6 and Pixi 4.8.1. It seems that the typescript definitions of pixi-viewport do not recognize the namespace of PIXI  

node_modules/pixi-viewport/@types/index.d.ts(47,9): error TS2503: Cannot find namespace 'PIXI'

I manually inserted an import of PIXI into the definition file, however, I dont know if there are other mechanism that are expected to do that already

**Comment by simonpeters** [comment]
Hi!

I'm running into the same issue, did you find a workaround?

**Comment by davidfig** [comment]
I'm not super familiar with typescript definition files. @ertrzyiks or @macropp, can you help with this one?

**Comment by macropp** [comment]
Hey, I saw you're importing Pixi as `import * as PIXI from 'pixi.js/dist/pixi.js';`, can you try `import * as PIXI from "pixi.js";`?

Importing pixi.js file from dist folder actually imports javascript file, so Typescript service doesn't get a chance to have a look if the module provides type definitions. I'd strongly suggest you never import specific files from npm modules, instead try to import modules or named exports.

**Comment by simonpeters** [comment]
Pixi breaks if you import with `import * as PIXI from "pixi.js";` see [issue](https://github.com/pixijs/pixi.js/issues/4921)

**Comment by macropp** [comment]
Seems like it's Angular 6 build that breaks. Not sure how to resolve the issue, if you have suggestions, they're welcome :)

**Comment by rpurushotma** [comment]
With Angular 7 I get the same error even with just "import * as PIXI from 'pixi.js'" The app itself works fine, though. I don't suppose there's any way to just suppress the errors? Is there documentation/examples anywhere about best ways to use this with angular/webpack?

![screen shot 2018-10-25 at 11 03 33 am](https://user-images.githubusercontent.com/4826791/47520966-870ebb00-d846-11e8-920d-f02852162815.png)

**Comment by uahic** [comment]
You may have a look at my library https://github.com/uahic/ng-pixi . I had the same problems, somehow I managed to go around :) take a look at the package.json 

You need for example  "@types/pixi.js": "^4.8.1",  ( npm install --save @types/pixi.js@4.8.1) But then there will be an issue in the index.d.ts of either pixi or pixi-viewport (cant remember), just modify the line where it will complain from PIXI.ticker.Ticker to PIXI.Ticker and you'll be fine

**Comment by rpurushotma** [comment]
thanks for the fix @uahic , I didn't run into any issues with Ticker yet (probably because my application doesn't use it yet). I did get this error:

ERROR in src/app/pages/fsli-work-page/evidence-modal/evidence-modal.component.ts(39,30): error TS2339: Property 'interaction' does not exist on type 'WebGLRenderer | CanvasRenderer'.
  Property 'interaction' does not exist on type 'WebGLRenderer'.

But typecasting app.renderer to :any  took care of that error.

**Comment by davidfig** [comment]
Feel free to reopen if this is still an issue.
